services:
  us4-db:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: int221
      MYSQL_PASSWORD: int221
      MYSQL_USER: dbconn
      MYSQL_DATABASE: us4db
    volumes:
      - ./script/dbscript.sql:/docker-entrypoint-initdb.d/dbscript.sql
  us4-be:
    image: us4-docker_us4-be
    restart: always
    environment:
      SPRING_DATASOURCE_PASSWORD: int221
      SPRING_DATASOURCE_USER: dbconn
      SPRING_DATASOURCE_NAME: us4db
      SPRING_DATASOURCE_URL: jdbc:mysql://us4-db:3306/us4db
      SERVER_PORT: 8443
      SERVER_ERROR_INCLUDE-MESSAGE: always
      SERVER_ERROR_INCLUDE-STACKTRACE: never
      JWT_SECRET: int222us4
      JWT_REFRESHSECRET: us4refresh
      JWT_EXPIRATIONINMS: 1800000
      JWT_REFRESHEXPIRATIONINMS: 86400000
      FILE_UPLOAD_PATH: /home/fileUploads/
      SPRING_SERVLET_MULTIPART_MAX-FILE-SIZE: 10MB
      SPRING_SERVLET_MULTIPART_MAX-REQUEST-SIZE: 15MB
  us4-fe:
    image: us4-docker_us4-fe
    restart: always
  us4-proxy:
    image: us4-docker_us4-proxy
    ports:
      - 443:443
      - 80:80
    restart: always