-- MySQL Script generated by MySQL Workbench
-- Sat May  7 16:43:29 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema us4db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema us4db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `us4db` DEFAULT CHARACTER SET utf8 ;
USE `us4db` ;
set names utf8;
-- -----------------------------------------------------
-- Table `us4db`.`eventCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `us4db`.`eventCategory` (
  `eventCategory_id` INT NOT NULL AUTO_INCREMENT,
  `eventCategoryName` VARCHAR(500) NOT NULL,
  `eventCategoryDescription` VARCHAR(2500) NULL,
  `eventDuration` INT NOT NULL,
  PRIMARY KEY (`eventCategory_id`))
ENGINE = InnoDB;
	
-- insert to eventCategory --
insert into `eventCategory`(`eventCategoryName`,`eventCategoryDescription`,`eventDuration`) values
('Project Management Clinic','ตารางนัดหมายนี้ใช้สำหรับนัดหมาย project management clinic ในวิชา INT221 integrated project I ให้นักศึกษาเตรียมเอกสารที่เกี่ยวข้องเพื่อแสดงระหว่างขอคำปรึกษา',30),
('DevOps/Infra Clinic','Use this event category for DevOps/Infra clinic.',20),
('Database Clinic','ตารางนัดหมายนี้ใช้สำหรับนัดหมาย database clinic ในวิชา INT221 integrated project I',15),
('Client-side Clinic','ตารางนัดหมายนี้ใช้สำหรับนัดหมาย client-side clinic ในวิชา INT221 integrated project I',30),
('Server-side Clinic',null,30);
-- -----------------------------------------------------
-- Table `us4db`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `us4db`.`event` (
  `event_id` INT NOT NULL AUTO_INCREMENT,
  `bookingName` VARCHAR(500) NOT NULL,
  `bookingEmail` VARCHAR(500) NOT NULL,
  `eventCategory_id` INT NOT NULL,
  `eventStartTime` DATETIME NOT NULL,
  `eventDuration` INT NOT NULL,
  `eventNotes` VARCHAR(2500) NULL,
  PRIMARY KEY (`event_id`, `eventCategory_id`),
  INDEX `_idx` (`eventCategory_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`eventCategory_id`)
    REFERENCES `us4db`.`eventCategory` (`eventCategory_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- Table `us4db`.`user`
CREATE TABLE IF NOT EXISTS `us4db`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` CHAR(90) NOT NULL,
  `role` ENUM('admin', 'lecturer', 'student') NOT NULL DEFAULT 'student',
  `createdOn` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updatedOn` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;

-- insert to event --
insert into `event`(`bookingName`,`bookingEmail`,`eventCategory_id`,`eventStartTime`,`eventDuration`,`eventNotes`) values
('Somchai Jaidee (OR-7)','somchai.jai@mail.kmutt.ac.th',2,'2022-05-23 6:30:00',30,null),
('Somsri Rakdee (SJ-3)','somsri.rak@mail.kmutt.ac.th',1,'2022-04-27 02:30:00',30,'ขอปรึกษาปัญหาเพื่อนไม่ช่วยทำงาน'),
('สมเกียรติ ขยันเรียน กลุ่ม TT-4','somkiat.kay@kmutt.ac.th',3,'2022-05-23 9:30:00',15,null);

-- insert to user --
INSERT INTO `user`(`name`,`email`,`password`,`role`) VALUES 
('OASIP ADMIN','oasip.admin@kmutt.ac.th','$argon2id$v=19$m=2048,t=3,p=1$WUJvVjE0WnNnNjY1OVcwZQ$JuvyP93enl+wDMZai5NVpg','admin'),
('Somchai Jaidee','somchai.jai@kmutt.ac.th','$argon2id$v=19$m=2048,t=3,p=1$bmtGb3dZNEFTaUZPOGI2bQ$3APBDKqu3seKDq6AL+f41A','lecturer'),
('Komkrid Rakdee','komkrid.rak@mail.kmutt.ac.th','$argon2id$v=19$m=2048,t=3,p=1$MTMzTXc4OWkxRTRKOFR2YQ$ALqpA412ZGjK8p0F3XqrEA','student');

create user 'dbconn'@'%' identified by 'int221';
grant all privileges on *.* TO 'dbconn'@'%';
flush privileges;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;